#!/usr/bin/env python3
import connexion
import sys
import os
sys.path.append(os.getcwd() + '/swagger_server')
from encoder import JSONEncoder

app = connexion.App(__name__, specification_dir='./swagger/')
app.app.json_encoder = JSONEncoder
app.add_api('swagger.yaml', arguments={'title': 'No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)'})

if __name__ == '__main__':
    app.run()
